/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto4.estruc;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.graphstream.graph.Edge;
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.graph.implementations.MultiGraph;
import org.graphstream.ui.view.View;
import org.graphstream.ui.view.Viewer;

/**
 *
 * @author Christian
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        jp_mapeo.setVisible(true);
        Viewer viewer = graph.display(true);
 	View view = viewer.getDefaultView();
	this.jp_mapeo.add((Component) view);
	this.repaint();
        this.setLocationRelativeTo(null);
        this.setTitle("Simulador de Emergencias (Proyecto 4-Estructura de Datos)");
        adminHospital.cargarArchivo();
        adminParamedico.cargarArchivo();
        adminAmbulancia.cargarArchivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_hospital = new javax.swing.JDialog();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jd_agregar_hospitales = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        tf_nombre_hospital = new javax.swing.JTextField();
        tf_direccion_hospital = new javax.swing.JTextField();
        tf_maxParamedicos_hospital = new javax.swing.JTextField();
        tf_maxAmbulancias_hospital = new javax.swing.JTextField();
        cb_ranking_hospital = new javax.swing.JComboBox();
        jd_eliminar_hospitales = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        cb_elim_hospital = new javax.swing.JComboBox();
        jButton8 = new javax.swing.JButton();
        jd_agregar_paramedicos = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        tf_nombre_paramedico = new javax.swing.JTextField();
        tf_edad_paramedico = new javax.swing.JTextField();
        tf_identidad_paramedico = new javax.swing.JTextField();
        cb_ranking_paramedico = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        cb_agregarHospital_paramedico = new javax.swing.JComboBox();
        jd_ambulancia = new javax.swing.JDialog();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jd_agregar_ambulancias = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        tf_numero_ambulancia = new javax.swing.JTextField();
        tf_año_ambulancia = new javax.swing.JTextField();
        tf_velocidadMax_ambulancia = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cb_agregarHospital_ambulancia = new javax.swing.JComboBox();
        jd_eliminar_ambulancias = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        cb_elim_ambulancia = new javax.swing.JComboBox();
        jButton13 = new javax.swing.JButton();
        jd_mapeo = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jp_mapeo = new javax.swing.JPanel();
        jd_agregarHospital_mapeo = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        cb_agregarHospital_mapeo = new javax.swing.JComboBox();
        jButton18 = new javax.swing.JButton();
        jd_agregarDomicilio_mapeo = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        tf_nombre_domicilio = new javax.swing.JTextField();
        tf_direccion_domicilio = new javax.swing.JTextField();
        jd_agregarConexion_mapeo = new javax.swing.JDialog();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        cb_conexionInicial = new javax.swing.JComboBox<String>();
        cb_conexionFinal = new javax.swing.JComboBox<String>();
        jButton24 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        tf_distancia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto4/estruc/hospital_318-115635 (agregar).png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto4/estruc/prohibido_318-123946.jpg"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_hospitalLayout = new javax.swing.GroupLayout(jd_hospital.getContentPane());
        jd_hospital.getContentPane().setLayout(jd_hospitalLayout);
        jd_hospitalLayout.setHorizontalGroup(
            jd_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_hospitalLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(50, 50, 50))
        );
        jd_hospitalLayout.setVerticalGroup(
            jd_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_hospitalLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jd_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7)
                    .addComponent(jButton6))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jLabel2.setText("Agregar Hospital");

        jLabel3.setText("Nombre");

        jLabel4.setText("Direccion");

        jLabel5.setText("Capacidad Maxima de Paramedicos");

        jLabel6.setText("Capacidad Maxima de Ambulancias");

        jLabel7.setText("Ranking");

        jButton5.setText("Agregar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        cb_ranking_hospital.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));

        javax.swing.GroupLayout jd_agregar_hospitalesLayout = new javax.swing.GroupLayout(jd_agregar_hospitales.getContentPane());
        jd_agregar_hospitales.getContentPane().setLayout(jd_agregar_hospitalesLayout);
        jd_agregar_hospitalesLayout.setHorizontalGroup(
            jd_agregar_hospitalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_hospitalesLayout.createSequentialGroup()
                .addGroup(jd_agregar_hospitalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregar_hospitalesLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jd_agregar_hospitalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jd_agregar_hospitalesLayout.createSequentialGroup()
                                .addGroup(jd_agregar_hospitalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_agregar_hospitalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel3))
                                .addGap(60, 60, 60)
                                .addGroup(jd_agregar_hospitalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_nombre_hospital)
                                    .addComponent(tf_direccion_hospital)
                                    .addComponent(tf_maxParamedicos_hospital)
                                    .addComponent(tf_maxAmbulancias_hospital)
                                    .addComponent(cb_ranking_hospital, 0, 110, Short.MAX_VALUE)))
                            .addGroup(jd_agregar_hospitalesLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel2))))
                    .addGroup(jd_agregar_hospitalesLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jButton5)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jd_agregar_hospitalesLayout.setVerticalGroup(
            jd_agregar_hospitalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_hospitalesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_agregar_hospitalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_nombre_hospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jd_agregar_hospitalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_direccion_hospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jd_agregar_hospitalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_maxParamedicos_hospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jd_agregar_hospitalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_maxAmbulancias_hospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jd_agregar_hospitalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_ranking_hospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jd_eliminar_hospitales.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jd_eliminar_hospitalesWindowOpened(evt);
            }
        });

        jLabel8.setText("Eliiminar Hospitales");

        jButton8.setText("Eliminar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_eliminar_hospitalesLayout = new javax.swing.GroupLayout(jd_eliminar_hospitales.getContentPane());
        jd_eliminar_hospitales.getContentPane().setLayout(jd_eliminar_hospitalesLayout);
        jd_eliminar_hospitalesLayout.setHorizontalGroup(
            jd_eliminar_hospitalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminar_hospitalesLayout.createSequentialGroup()
                .addGroup(jd_eliminar_hospitalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_eliminar_hospitalesLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel8))
                    .addGroup(jd_eliminar_hospitalesLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButton8))
                    .addGroup(jd_eliminar_hospitalesLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(cb_elim_hospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jd_eliminar_hospitalesLayout.setVerticalGroup(
            jd_eliminar_hospitalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminar_hospitalesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(41, 41, 41)
                .addComponent(cb_elim_hospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton8)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jLabel9.setText("Agregar Paramedicos");

        jLabel10.setText("Nombre");

        jLabel11.setText("Edad");

        jLabel12.setText("Identidad");

        jLabel13.setText("Ranking");

        jButton9.setText("Agregar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        cb_ranking_paramedico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));

        jLabel20.setText("Hospital a Agregarse");

        javax.swing.GroupLayout jd_agregar_paramedicosLayout = new javax.swing.GroupLayout(jd_agregar_paramedicos.getContentPane());
        jd_agregar_paramedicos.getContentPane().setLayout(jd_agregar_paramedicosLayout);
        jd_agregar_paramedicosLayout.setHorizontalGroup(
            jd_agregar_paramedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_paramedicosLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jd_agregar_paramedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregar_paramedicosLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addContainerGap())
                    .addGroup(jd_agregar_paramedicosLayout.createSequentialGroup()
                        .addGroup(jd_agregar_paramedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGroup(jd_agregar_paramedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_agregar_paramedicosLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jd_agregar_paramedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jd_agregar_paramedicosLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton9)))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregar_paramedicosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addGroup(jd_agregar_paramedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cb_agregarHospital_paramedico, 0, 110, Short.MAX_VALUE)
                                    .addGroup(jd_agregar_paramedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_nombre_paramedico)
                                        .addComponent(tf_edad_paramedico)
                                        .addComponent(tf_identidad_paramedico)
                                        .addComponent(cb_ranking_paramedico, javax.swing.GroupLayout.Alignment.TRAILING, 0, 110, Short.MAX_VALUE)))
                                .addGap(79, 79, 79))))))
        );
        jd_agregar_paramedicosLayout.setVerticalGroup(
            jd_agregar_paramedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_paramedicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jd_agregar_paramedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_nombre_paramedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jd_agregar_paramedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_edad_paramedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jd_agregar_paramedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_identidad_paramedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jd_agregar_paramedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cb_ranking_paramedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jd_agregar_paramedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cb_agregarHospital_paramedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jButton9)
                .addGap(41, 41, 41))
        );

        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Christian\\Pictures\\ambulancecar_ambulancia_4663.png")); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Christian\\Pictures\\prohibido_318-123946.jpg")); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_ambulanciaLayout = new javax.swing.GroupLayout(jd_ambulancia.getContentPane());
        jd_ambulancia.getContentPane().setLayout(jd_ambulanciaLayout);
        jd_ambulanciaLayout.setHorizontalGroup(
            jd_ambulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ambulanciaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(25, 25, 25))
        );
        jd_ambulanciaLayout.setVerticalGroup(
            jd_ambulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ambulanciaLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jd_ambulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton11)
                    .addComponent(jButton10))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jd_agregar_ambulancias.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jd_agregar_ambulanciasWindowOpened(evt);
            }
        });

        jLabel14.setText("Agregar Ambulancia");

        jLabel15.setText("Numero");

        jLabel16.setText("Año");

        jLabel17.setText("Velocidad Maxima");

        jButton12.setText("Agregar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel19.setText("Hospital a Agregarse");

        javax.swing.GroupLayout jd_agregar_ambulanciasLayout = new javax.swing.GroupLayout(jd_agregar_ambulancias.getContentPane());
        jd_agregar_ambulancias.getContentPane().setLayout(jd_agregar_ambulanciasLayout);
        jd_agregar_ambulanciasLayout.setHorizontalGroup(
            jd_agregar_ambulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_ambulanciasLayout.createSequentialGroup()
                .addGroup(jd_agregar_ambulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_agregar_ambulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_agregar_ambulanciasLayout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addGroup(jd_agregar_ambulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel15)
                                .addComponent(jLabel17)
                                .addComponent(jLabel19))
                            .addGap(53, 53, 53)
                            .addGroup(jd_agregar_ambulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_numero_ambulancia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_año_ambulancia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jd_agregar_ambulanciasLayout.createSequentialGroup()
                            .addGap(157, 157, 157)
                            .addGroup(jd_agregar_ambulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addGroup(jd_agregar_ambulanciasLayout.createSequentialGroup()
                                    .addGap(7, 7, 7)
                                    .addComponent(jButton12)))))
                    .addGroup(jd_agregar_ambulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cb_agregarHospital_ambulancia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_velocidadMax_ambulancia, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jd_agregar_ambulanciasLayout.setVerticalGroup(
            jd_agregar_ambulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_ambulanciasLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jd_agregar_ambulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_numero_ambulancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jd_agregar_ambulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_año_ambulancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jd_agregar_ambulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_velocidadMax_ambulancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jd_agregar_ambulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cb_agregarHospital_ambulancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton12)
                .addGap(29, 29, 29))
        );

        jd_eliminar_ambulancias.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jd_eliminar_ambulanciasWindowOpened(evt);
            }
        });

        jLabel18.setText("Eliminar Ambulancias");

        jButton13.setText("Eliminar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_eliminar_ambulanciasLayout = new javax.swing.GroupLayout(jd_eliminar_ambulancias.getContentPane());
        jd_eliminar_ambulancias.getContentPane().setLayout(jd_eliminar_ambulanciasLayout);
        jd_eliminar_ambulanciasLayout.setHorizontalGroup(
            jd_eliminar_ambulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminar_ambulanciasLayout.createSequentialGroup()
                .addGroup(jd_eliminar_ambulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_eliminar_ambulanciasLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel18))
                    .addGroup(jd_eliminar_ambulanciasLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(cb_elim_ambulancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_eliminar_ambulanciasLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButton13)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jd_eliminar_ambulanciasLayout.setVerticalGroup(
            jd_eliminar_ambulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminar_ambulanciasLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel18)
                .addGap(45, 45, 45)
                .addComponent(cb_elim_ambulancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButton13)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Panel de Mapeo");

        jButton14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Christian\\Pictures\\hospital_318-115717.png")); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Christian\\Pictures\\plug-powder-cord-two-people-pull-plugs_112698796.jpg")); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Christian\\Pictures\\casa.jpg")); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("Emergencia");

        jp_mapeo.setPreferredSize(new java.awt.Dimension(900, 600));

        javax.swing.GroupLayout jp_mapeoLayout = new javax.swing.GroupLayout(jp_mapeo);
        jp_mapeo.setLayout(jp_mapeoLayout);
        jp_mapeoLayout.setHorizontalGroup(
            jp_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jp_mapeoLayout.setVerticalGroup(
            jp_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_mapeoLayout = new javax.swing.GroupLayout(jd_mapeo.getContentPane());
        jd_mapeo.getContentPane().setLayout(jd_mapeoLayout);
        jd_mapeoLayout.setHorizontalGroup(
            jd_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mapeoLayout.createSequentialGroup()
                .addGroup(jd_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_mapeoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jp_mapeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_mapeoLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jd_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_mapeoLayout.createSequentialGroup()
                                .addComponent(jButton14)
                                .addGap(75, 75, 75)
                                .addComponent(jButton15)
                                .addGap(61, 61, 61)
                                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_mapeoLayout.createSequentialGroup()
                                .addGap(279, 279, 279)
                                .addComponent(jButton17))))
                    .addGroup(jd_mapeoLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel21)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_mapeoLayout.setVerticalGroup(
            jd_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mapeoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_mapeo, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton17)
                .addGap(0, 182, Short.MAX_VALUE))
        );

        jd_agregarHospital_mapeo.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jd_agregarHospital_mapeoWindowOpened(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Agregar Hospital al Mapeo");

        jButton18.setText("Agregar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarHospital_mapeoLayout = new javax.swing.GroupLayout(jd_agregarHospital_mapeo.getContentPane());
        jd_agregarHospital_mapeo.getContentPane().setLayout(jd_agregarHospital_mapeoLayout);
        jd_agregarHospital_mapeoLayout.setHorizontalGroup(
            jd_agregarHospital_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarHospital_mapeoLayout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(119, 119, 119))
            .addGroup(jd_agregarHospital_mapeoLayout.createSequentialGroup()
                .addGroup(jd_agregarHospital_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarHospital_mapeoLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(cb_agregarHospital_mapeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_agregarHospital_mapeoLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButton18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_agregarHospital_mapeoLayout.setVerticalGroup(
            jd_agregarHospital_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarHospital_mapeoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel22)
                .addGap(45, 45, 45)
                .addComponent(cb_agregarHospital_mapeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton18)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jLabel23.setText("Agregar Domicilio al Mapeo");

        jLabel24.setText("Nombre");

        jLabel25.setText("Direccion");

        jButton19.setText("Agregar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarDomicilio_mapeoLayout = new javax.swing.GroupLayout(jd_agregarDomicilio_mapeo.getContentPane());
        jd_agregarDomicilio_mapeo.getContentPane().setLayout(jd_agregarDomicilio_mapeoLayout);
        jd_agregarDomicilio_mapeoLayout.setHorizontalGroup(
            jd_agregarDomicilio_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarDomicilio_mapeoLayout.createSequentialGroup()
                .addGroup(jd_agregarDomicilio_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarDomicilio_mapeoLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel23))
                    .addGroup(jd_agregarDomicilio_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_agregarDomicilio_mapeoLayout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addGroup(jd_agregarDomicilio_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel25)
                                .addComponent(jLabel24))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                            .addGroup(jd_agregarDomicilio_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nombre_domicilio)
                                .addComponent(tf_direccion_domicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_agregarDomicilio_mapeoLayout.createSequentialGroup()
                            .addGap(159, 159, 159)
                            .addComponent(jButton19))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jd_agregarDomicilio_mapeoLayout.setVerticalGroup(
            jd_agregarDomicilio_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarDomicilio_mapeoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel23)
                .addGap(22, 22, 22)
                .addGroup(jd_agregarDomicilio_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tf_nombre_domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jd_agregarDomicilio_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tf_direccion_domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton19)
                .addGap(85, 85, 85))
        );

        jd_agregarConexion_mapeo.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jd_agregarConexion_mapeoWindowOpened(evt);
            }
        });

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Destino");

        jLabel40.setText("Agregar Conexion");

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Origen");

        jButton24.setText("Conectar");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("Distancia");

        javax.swing.GroupLayout jd_agregarConexion_mapeoLayout = new javax.swing.GroupLayout(jd_agregarConexion_mapeo.getContentPane());
        jd_agregarConexion_mapeo.getContentPane().setLayout(jd_agregarConexion_mapeoLayout);
        jd_agregarConexion_mapeoLayout.setHorizontalGroup(
            jd_agregarConexion_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarConexion_mapeoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_agregarConexion_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarConexion_mapeoLayout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarConexion_mapeoLayout.createSequentialGroup()
                        .addComponent(cb_conexionInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(cb_conexionFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
            .addGroup(jd_agregarConexion_mapeoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jd_agregarConexion_mapeoLayout.createSequentialGroup()
                .addGroup(jd_agregarConexion_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarConexion_mapeoLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_agregarConexion_mapeoLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(tf_distancia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_agregarConexion_mapeoLayout.setVerticalGroup(
            jd_agregarConexion_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarConexion_mapeoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel40)
                .addGap(18, 18, 18)
                .addGroup(jd_agregarConexion_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_agregarConexion_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_conexionInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_conexionFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jd_agregarConexion_mapeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(tf_distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jButton24)
                .addGap(35, 35, 35))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Simulador de Hospitales");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto4/estruc/hospital_318-115717.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto4/estruc/paramedico_318-117970.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto4/estruc/vista-lateral-ambulancia_318-77652.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Christian\\Pictures\\mapeo.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1)
                        .addGap(61, 61, 61)
                        .addComponent(jButton2)
                        .addGap(75, 75, 75)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        adminHospital.escribirArchivo();
        adminParamedico.escribirArchivo();
        adminAmbulancia.escribirArchivo();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.jd_hospital.setModal(true);
        this.jd_hospital.pack();
        this.jd_hospital.setLocationRelativeTo(this);
        this.jd_hospital.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.jd_agregar_hospitales.setModal(true);
        this.jd_agregar_hospitales.pack();
        this.jd_agregar_hospitales.setLocationRelativeTo(this);
        this.jd_agregar_hospitales.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        adminHospital.getListaHospitales().add(new Hospital(this.tf_nombre_hospital.getText(),this.tf_direccion_hospital.getText()
                ,Integer.parseInt(this.tf_maxParamedicos_hospital.getText())
                ,Integer.parseInt(this.tf_maxAmbulancias_hospital.getText())
                ,this.cb_ranking_hospital.getSelectedItem().toString()));
        this.tf_nombre_hospital.setText("");
        this.tf_direccion_hospital.setText("");
        this.tf_maxParamedicos_hospital.setText("");
        this.tf_maxAmbulancias_hospital.setText("");
        this.cb_ranking_hospital.setSelectedIndex(0);
        JOptionPane.showMessageDialog(this, "El hospital se ha agregado. ");
        this.jd_agregar_hospitales.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jd_eliminar_hospitalesWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_eliminar_hospitalesWindowOpened
        DefaultComboBoxModel modelo=(DefaultComboBoxModel) cb_elim_hospital.getModel();
        for (int i = 0; i < adminHospital.getListaHospitales().size(); i++) {
            modelo.addElement(adminHospital.getListaHospitales().get(i).getNombre());
            cb_elim_hospital.setModel(modelo);
        }
    }//GEN-LAST:event_jd_eliminar_hospitalesWindowOpened

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int seguro=JOptionPane.showConfirmDialog(this, "Esta seguro de que quiere borrar este hospital?");
        if (seguro==JOptionPane.YES_OPTION) {
            DefaultComboBoxModel modelo=(DefaultComboBoxModel) cb_elim_hospital.getModel();
            int posicion=modelo.getIndexOf(modelo.getSelectedItem());
            modelo.removeElement(modelo.getSelectedItem());
            adminHospital.getListaHospitales().remove(posicion);
            JOptionPane.showMessageDialog(this, "El hospital ha sido eliminado.");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.jd_agregar_paramedicos.setModal(true);
        this.jd_agregar_paramedicos.pack();
        this.jd_agregar_paramedicos.setLocationRelativeTo(this);
        this.jd_agregar_paramedicos.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int posicion=this.cb_agregarHospital_paramedico.getSelectedIndex();
        if (adminHospital.getListaHospitales().get(posicion).getParamedicos().size()<
                adminHospital.getListaHospitales().get(posicion).getCapParamedicos()) {
                adminParamedico.getListaParamedicos().add(new Paramedico(this.tf_nombre_paramedico.getText()
                    ,Integer.parseInt(this.tf_edad_paramedico.getText())
                    ,Integer.parseInt(this.tf_identidad_paramedico.getText())
                    ,(Ranking)this.cb_ranking_hospital.getSelectedItem()
                    ,this.cb_agregarHospital_paramedico.getSelectedItem().toString()));
            String nombreHospital = this.cb_agregarHospital_paramedico.getSelectedItem().toString();
            for (int i = 0; i < adminHospital.getListaHospitales().size(); i++) {
                if (adminHospital.getListaHospitales().get(i).getNombre().equalsIgnoreCase(nombreHospital)) {
                    adminHospital.getListaHospitales().get(i).getParamedicos().add(new Paramedico(this.tf_nombre_paramedico.getText()
                    ,Integer.parseInt(this.tf_edad_paramedico.getText())
                    ,Integer.parseInt(this.tf_identidad_paramedico.getText())
                    ,(Ranking)this.cb_ranking_hospital.getSelectedItem()
                    ,this.cb_agregarHospital_paramedico.getSelectedItem().toString()));
                }
            }
            this.tf_nombre_paramedico.setText("");
            this.tf_edad_paramedico.setText("");
            this.tf_identidad_paramedico.setText("");
            this.cb_ranking_paramedico.setSelectedIndex(0);
            JOptionPane.showMessageDialog(this, "El paramedico se ha agregado. ");
            this.jd_agregar_paramedicos.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Se ha llegado al limite de paramedicos. ");
            this.jd_agregar_paramedicos.dispose();
        } 
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.jd_eliminar_hospitales.setModal(true);
        this.jd_eliminar_hospitales.pack();
        this.jd_eliminar_hospitales.setLocationRelativeTo(this);
        this.jd_eliminar_hospitales.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.jd_agregar_ambulancias.setModal(true);
        this.jd_agregar_ambulancias.pack();
        this.jd_agregar_ambulancias.setLocationRelativeTo(this);
        this.jd_agregar_ambulancias.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.jd_eliminar_ambulancias.setModal(true);
        this.jd_eliminar_ambulancias.pack();
        this.jd_eliminar_ambulancias.setLocationRelativeTo(this);
        this.jd_eliminar_ambulancias.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        int posicion=this.cb_agregarHospital_ambulancia.getSelectedIndex();
        if ((!adminHospital.getListaHospitales().get(posicion).getAmbulancias().isEmpty()&&
                adminHospital.getListaHospitales().get(posicion).getAmbulancias().size()<=
                adminHospital.getListaHospitales().get(posicion).getCapAmbulancias())
                ||adminHospital.getListaHospitales().get(posicion).getAmbulancias().isEmpty()) {
                adminAmbulancia.getListaAmbulancias().add(new Ambulancia(Integer.parseInt(this.tf_numero_ambulancia.getText())
                    ,Integer.parseInt(this.tf_año_ambulancia.getText())
                    ,Integer.parseInt(this.tf_velocidadMax_ambulancia.getText())
                    ,this.cb_agregarHospital_ambulancia.getSelectedItem().toString()));
            String nombreHospital = this.cb_agregarHospital_ambulancia.getSelectedItem().toString();
            for (int i = 0; i < adminHospital.getListaHospitales().size(); i++) {
                if (adminHospital.getListaHospitales().get(i).getNombre().equalsIgnoreCase(nombreHospital)) {
                    adminHospital.getListaHospitales().get(i).getAmbulancias().add(new Ambulancia(Integer.parseInt(this.tf_numero_ambulancia.getText())
                    ,Integer.parseInt(this.tf_año_ambulancia.getText())
                    ,Integer.parseInt(this.tf_velocidadMax_ambulancia.getText())
                    ,this.cb_agregarHospital_ambulancia.getSelectedItem().toString()));
                }
            }
            this.tf_numero_ambulancia.setText("");
            this.tf_año_ambulancia.setText("");
            this.tf_velocidadMax_ambulancia.setText("");
            JOptionPane.showMessageDialog(this, "La ambulancia se ha agregado. ");
            this.jd_agregar_ambulancias.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Se ha llegado al limite de ambulancias. ");
            this.jd_agregar_ambulancias.dispose();
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int seguro=JOptionPane.showConfirmDialog(this, "Esta seguro de que quiere borrar este hospital?");
        if (seguro==JOptionPane.YES_OPTION) {
            DefaultComboBoxModel modelo=(DefaultComboBoxModel) cb_elim_ambulancia.getModel();
            int posicion=modelo.getIndexOf(modelo.getSelectedItem());
            modelo.removeElement(modelo.getSelectedItem());
            adminAmbulancia.getListaHospitales().remove(posicion);
            JOptionPane.showMessageDialog(this, "La ambulancia ha sido eliminada.");
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jd_eliminar_ambulanciasWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_eliminar_ambulanciasWindowOpened
        DefaultComboBoxModel modelo=(DefaultComboBoxModel) cb_elim_ambulancia.getModel();
        for (int i = 0; i < adminAmbulancia.getListaAmbulancias().size(); i++) {
            modelo.addElement(adminAmbulancia.getListaAmbulancias().get(i).getNumero());
            cb_elim_ambulancia.setModel(modelo);
        }
    }//GEN-LAST:event_jd_eliminar_ambulanciasWindowOpened

    private void jd_agregar_ambulanciasWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_agregar_ambulanciasWindowOpened
        if (!adminHospital.getListaHospitales().isEmpty()) {
            DefaultComboBoxModel modelo=(DefaultComboBoxModel) this.cb_agregarHospital_ambulancia.getModel();
            for (int i = 0; i < adminHospital.getListaHospitales().size(); i++) {
                modelo.addElement(adminHospital.getListaHospitales().get(i).getNombre());
                this.cb_agregarHospital_ambulancia.setModel(modelo);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Agregue hospitales para agregar ambulancias.");
            this.jd_agregar_ambulancias.dispose();
        }
    }//GEN-LAST:event_jd_agregar_ambulanciasWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.jd_ambulancia.setModal(true);
        this.jd_ambulancia.pack();
        this.jd_ambulancia.setLocationRelativeTo(this);
        this.jd_ambulancia.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.jd_mapeo.setModal(true);
        this.jd_mapeo.pack();
        this.jd_mapeo.setLocationRelativeTo(this);
        this.jd_mapeo.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jd_agregarHospital_mapeoWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_agregarHospital_mapeoWindowOpened
        DefaultComboBoxModel modelo=(DefaultComboBoxModel) cb_agregarHospital_mapeo.getModel();
        for (int i = 0; i < adminHospital.getListaHospitales().size(); i++) {
            modelo.addElement(adminHospital.getListaHospitales().get(i).getNombre());
            cb_agregarHospital_mapeo.setModel(modelo);
        }
    }//GEN-LAST:event_jd_agregarHospital_mapeoWindowOpened

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        String hospital = this.cb_agregarHospital_mapeo.getSelectedItem().toString();
        Node nodo = graph.addNode(hospital);
        nodo.addAttribute("ui.label", hospital);
        this.jd_agregarHospital_mapeo.dispose();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        Domicilio domicilio = new Domicilio(this.tf_nombre_domicilio.getText(), this.tf_direccion_domicilio.getText());
        listaDomicilios.add(domicilio);
        Node nodo = graph.addNode(domicilio.toString());
        nodo.addAttribute("ui.label", domicilio.toString());
        this.tf_nombre_domicilio.setText("");
        this.tf_direccion_domicilio.setText("");
        this.jd_agregarDomicilio_mapeo.dispose();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        this.jd_agregarHospital_mapeo.setModal(true);
        this.jd_agregarHospital_mapeo.pack();
        this.jd_agregarHospital_mapeo.setLocationRelativeTo(this);
        this.jd_agregarHospital_mapeo.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        this.jd_agregarDomicilio_mapeo.setModal(true);
        this.jd_agregarDomicilio_mapeo.pack();
        this.jd_agregarDomicilio_mapeo.setLocationRelativeTo(this);
        this.jd_agregarDomicilio_mapeo.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        this.jd_agregarConexion_mapeo.setModal(true);
        this.jd_agregarConexion_mapeo.pack();
        this.jd_agregarConexion_mapeo.setLocationRelativeTo(this);
        this.jd_agregarConexion_mapeo.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jd_agregarConexion_mapeoWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_agregarConexion_mapeoWindowOpened
        DefaultComboBoxModel modelo=(DefaultComboBoxModel) cb_conexionInicial.getModel();
        for (int i = 0; i < adminHospital.getListaHospitales().size(); i++) {
            modelo.addElement(adminHospital.getListaHospitales().get(i).getNombre());
            cb_conexionInicial.setModel(modelo);
        }
        DefaultComboBoxModel modelo2=(DefaultComboBoxModel) cb_conexionFinal.getModel();
        for (int i = 0; i < listaDomicilios.size(); i++) {
            modelo2.addElement(listaDomicilios.get(i).getNombre());
            cb_conexionFinal.setModel(modelo2);
        }
    }//GEN-LAST:event_jd_agregarConexion_mapeoWindowOpened

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        Object conexionInicial = this.cb_conexionInicial.getSelectedItem();
        Object conexionFinal = this.cb_conexionFinal.getSelectedItem();
        String distancia = this.tf_distancia.getText();
        Edge edge = graph.addEdge(conexionInicial.toString() + "-" + conexionFinal.toString()
            , conexionInicial.toString(), conexionFinal.toString());
        edge.addAttribute("ui.label", distancia);
        this.tf_distancia.setText("");
        this.jd_agregarConexion_mapeo.dispose();
    }//GEN-LAST:event_jButton24ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb_agregarHospital_ambulancia;
    private javax.swing.JComboBox cb_agregarHospital_mapeo;
    private javax.swing.JComboBox cb_agregarHospital_paramedico;
    private javax.swing.JComboBox<String> cb_conexionFinal;
    private javax.swing.JComboBox<String> cb_conexionInicial;
    private javax.swing.JComboBox cb_elim_ambulancia;
    private javax.swing.JComboBox cb_elim_hospital;
    private javax.swing.JComboBox cb_ranking_hospital;
    private javax.swing.JComboBox cb_ranking_paramedico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JDialog jd_agregarConexion_mapeo;
    private javax.swing.JDialog jd_agregarDomicilio_mapeo;
    private javax.swing.JDialog jd_agregarHospital_mapeo;
    private javax.swing.JDialog jd_agregar_ambulancias;
    private javax.swing.JDialog jd_agregar_hospitales;
    private javax.swing.JDialog jd_agregar_paramedicos;
    private javax.swing.JDialog jd_ambulancia;
    private javax.swing.JDialog jd_eliminar_ambulancias;
    private javax.swing.JDialog jd_eliminar_hospitales;
    private javax.swing.JDialog jd_hospital;
    private javax.swing.JDialog jd_mapeo;
    private javax.swing.JPanel jp_mapeo;
    private javax.swing.JTextField tf_año_ambulancia;
    private javax.swing.JTextField tf_direccion_domicilio;
    private javax.swing.JTextField tf_direccion_hospital;
    private javax.swing.JTextField tf_distancia;
    private javax.swing.JTextField tf_edad_paramedico;
    private javax.swing.JTextField tf_identidad_paramedico;
    private javax.swing.JTextField tf_maxAmbulancias_hospital;
    private javax.swing.JTextField tf_maxParamedicos_hospital;
    private javax.swing.JTextField tf_nombre_domicilio;
    private javax.swing.JTextField tf_nombre_hospital;
    private javax.swing.JTextField tf_nombre_paramedico;
    private javax.swing.JTextField tf_numero_ambulancia;
    private javax.swing.JTextField tf_velocidadMax_ambulancia;
    // End of variables declaration//GEN-END:variables
Graph graph = new MultiGraph("Graffo");
ArrayList<Domicilio> listaDomicilios= new ArrayList();
administrarHospitales adminHospital= new administrarHospitales("./hospitales.txt");
administrarParamedicos adminParamedico= new administrarParamedicos("./paramedicos.txt");
administrarAmbulancias adminAmbulancia= new administrarAmbulancias("./ambulancias.txt");
}
